const path = './pics/product_pics/';

exports.products = {
	"t-shirt-asocialface-black": {
		id: "t-shirt-asocialface-black",
		name: 'T-shirt Asocialface black',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-asocialface-black-1.jpg',
		prototype1: path + 'asocial__t-shirt-asocialface-black-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-asocialface-black-proto-2.jpg'
	},
	"t-shirt-asocialface-bw": {
		id: "t-shirt-asocialface-bw",
		name: 'T-shirt Asocialface bw',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-asocialface-bw-1.jpg',
		prototype1: path + 'asocial__t-shirt-asocialface-bw-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-asocialface-bw-proto-2.jpg'
	},
	"t-shirt-asocialface-pink": {
		id: "t-shirt-asocialface-pink",
		name: 'T-shirt Asocialface pink',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-asocialface-pink-1.jpg',
		prototype1: path + 'asocial__t-shirt-asocialface-pink-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-asocialface-pink-proto-2.jpg'
	},
	"t-shirt-asocialface-white": {
		id: "t-shirt-asocialface-white",
		name: 'T-shirt Asocialface white',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-asocialface-white-1.jpg',
		prototype1: path + 'asocial__t-shirt-asocialface-white-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-asocialface-white-proto-2.jpg'
	},
	"asocial__t-shirt-fa-bw-1": {
		id: "asocial__t-shirt-fa-bw-1",
		name: 'T-shirt Fa b/w',
		sizes: 'sizes: s, m, l',
		price: 'price: 2500 RUB',
		material: '100% cotton',
		decoration: 'serigraphy',
		src: path + 'asocial__t-shirt-fa-bw-1.jpg',
		src2: path + 'asocial__t-shirt-fa-bw-2.jpg',
		prototype1: path + 'asocial__t-shirt-fa-bw-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-fa-bw-proto-2.jpg'
	},
	"asocial__t-shirt-fa-white-1": {
		id: "asocial__t-shirt-fa-white-1",
		name: 'T-shirt Fa white',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'serigraphy',
		src: path + 'asocial__t-shirt-fa-white-1.jpg',
		src2: path + 'asocial__t-shirt-fa-white-2.jpg',
		prototype1: path + 'asocial__t-shirt-fa-white-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-fa-white-proto-2.jpg'
	},
	"asocial__t-shirt-goth-black": {
		id: "asocial__t-shirt-goth-black",
		name: 'T-shirt Goth black',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-goth-black-1.jpg',
		prototype1: path + 'asocial__t-shirt-goth-black-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-goth-black-proto-2.jpg'
	},
	"asocial__t-shirt-goth-bw": {
		id: "asocial__t-shirt-goth-bw",
		name: 'T-shirt Goth b/w',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-goth-bw-1.jpg',
		prototype1: path + 'asocial__t-shirt-goth-bw-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-goth-bw-proto-2.jpg'
	},
	"asocial__t-shirt-goth-pink": {
		id: "asocial__t-shirt-goth-pink",
		name: 'T-shirt Goth pink',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-goth-pink-1.jpg',
		prototype1: path + 'asocial__t-shirt-goth-pink-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-goth-pink-proto-2.jpg'
	},
	"asocial__t-shirt-goth-white": {
		id: "asocial__t-shirt-goth-white",
		name: 'T-shirt Goth white',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-goth-white-1.jpg',
		prototype1: path + 'asocial__t-shirt-goth-white-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-goth-white-proto-2.jpg'
	},
	"asocial__t-shirt-mediumcool-black-1": {
		id: "asocial__t-shirt-mediumcool-black-1",
		name: 'T-shirt Medium cool black',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-mediumcool-black-1.jpg',
		src2: path + 'asocial__t-shirt-mediumcool-black-2.jpg',
		prototype1: path + 'asocial__t-shirt-mediumcool-black-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-mediumcool-black-proto-2.jpg'
	},
	"asocial__t-shirt-mediumcool-pink-1": {
		id: "asocial__t-shirt-mediumcool-pink-1",
		name: 'T-shirt Medium cool pink',
		sizes: 'sizes: s, m, l',
		price: 'price: 2300 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-mediumcool-pink-1.jpg',
		src2: path + 'asocial__t-shirt-mediumcool-pink-2.jpg',
		prototype1: path + 'asocial__t-shirt-mediumcool-pink-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-mediumcool-pink-proto-2.jpg'
	},
	"asocial__t-shirt-mediumcool-pw": {
		id: "asocial__t-shirt-mediumcool-pw",
		name: 'T-shirt Medium cool p/w',
		sizes: 'sizes: s, m, l',
		price: 'price: 2500 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__t-shirt-mediumcool-pw-1.jpg',
		src2: path + 'asocial__t-shirt-mediumcool-pw-2.jpg',
		prototype1: path + 'asocial__t-shirt-mediumcool-pw-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-mediumcool-pw-proto-2.jpg'
	},
	"asocial__t-shirt-soldout-white-1": {
		id: "asocial__t-shirt-soldout-white-1",
		name: 'T-shirt Sold out white',
		sizes: 'sizes: s, m, l',
		price: 'price: 2800 RUB',
		material: '100% cotton',
		decoration: 'serigraphy',
		src: path + 'asocial__t-shirt-soldout-white-1.jpg',
		src2: path + 'asocial__t-shirt-soldout-white-2.jpg',
		prototype1: path + 'asocial__t-shirt-soldout-white-proto-1.jpg',
		prototype2: path + 'asocial__t-shirt-soldout-white-proto-2.jpg'
	},
	"cap-asocialface-black": {
		id: "cap-asocialface-black",
		name: 'Cap Asocial face black',
		sizes: 'one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-asocialface-black-1.jpg',
		prototype1: path + 'asocial__cap-asocialface-black-proto-1.png',
		prototype2: path + 'asocial__cap-asocialface-black-proto-2.png'
	},
	"cap-asocialface-white": {
		id: "cap-asocialface-white",
		name: 'Cap Asocial face white',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-asocialface-white.jpg',
		prototype1: path + 'asocial__cap-asocialface-white-proto-1.png',
		prototype2: path + 'asocial__cap-asocialface-white-proto-2.jpg'
	},
	"cap-asocialface-pink": {
		id: "cap-asocialface-pink",
		name: 'Cap Asocial face pink',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-asocialface-pink-1.jpg',
		prototype1: path + 'asocial__cap-asocialface-pink-proto-1.png',
		prototype2: path + 'asocial__cap-asocialface-pink-proto-2.png'
	},
	"asocial__cap-goth-black": {
		id: "asocial__cap-goth-black",
		name: 'Cap Goth black',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-goth-black-1.jpg',
		prototype1: path + 'asocial__cap-goth-black-proto-1.png',
		prototype2: path + 'asocial__cap-goth-black-proto-2.jpg'
	},
	"asocial__cap-goth-pink": {
		id: "asocial__cap-goth-pink",
		name: 'Cap Goth pink',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-goth-pink-1.jpg',
		prototype1: path + 'asocial__cap-goth-pink-proto-1.png',
		prototype2: path + 'asocial__cap-goth-pink-proto-2.jpg'
	},
	"asocial__cap-goth-white": {
		id: "asocial__cap-goth-white",
		name: 'Cap Goth white',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-goth-white-1.jpg',
		prototype1: path + 'asocial__cap-goth-white-proto-1.png',
		prototype2: path + 'asocial__cap-goth-white-proto-2.jpg'
	},
	"asocial__cap-mediumcool-black": {
		id: "asocial__cap-mediumcool-black",
		name: 'Cap Medium cool black',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-mediumcool-black-1.jpg',
		prototype1: path + 'asocial__cap-mediumcool-black-proto-1.png',
		prototype2: path + 'asocial__cap-mediumcool-black-proto-2.jpg'
	},
	"asocial__cap-mediumcool-pink": {
		id: "asocial__cap-mediumcool-pink",
		name: 'Cap Medium cool pink',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-mediumcool-pink-1.jpg',
		prototype1: path + 'asocial__cap-mediumcool-pink-proto-1.png',
		prototype2: path + 'asocial__cap-mediumcool-pink-proto-2.jpg'
	},
	"asocial__cap-mediumcool-white": {
		id: "asocial__cap-mediumcool-white",
		name: 'Cap Medium cool white',
		sizes: 'sizes: one size',
		price: 'price: 2100 RUB',
		material: '100% cotton',
		decoration: 'embroidery',
		src: path + 'asocial__cap-mediumcool-white-1.jpg',
		prototype1: path + 'asocial__cap-mediumcool-white-proto-1.png',
		prototype2: path + 'asocial__cap-mediumcool-white-proto-2.jpg'
	}
};
